# Generated by Django 5.2.4 on 2025-09-02 00:47

import django.utils.timezone
import my_django_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('freq', my_django_app.fields.ChoiceIntegerField([(0, 'Yearly'), (1, 'Monthly'), (2, 'Weekly'), (3, 'Daily'), (4, 'Hourly'), (5, 'Minutely'), (6, 'Secondly')], 0)),
                ('interval', my_django_app.fields.LimitedDecimalField(decimal_places=2, max_digits=10)),
                ('by_week_day', my_django_app.fields.ChoicesStringArrayField(blank=True, choices=['MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU'], default=list)),
                ('by_month_day', my_django_app.fields.ChoicesNumberArrayField(blank=True, choices=range(1, 32), default=list)),
                ('by_month', my_django_app.fields.ChoicesNumberArrayField(blank=True, choices=range(1, 13), default=list)),
                ('by_year_day', my_django_app.fields.ChoicesNumberArrayField(blank=True, choices=range(1, 367), default=list)),
                ('by_week_no', my_django_app.fields.ChoicesNumberArrayField(blank=True, choices=range(1, 54), default=list)),
                ('by_hour', my_django_app.fields.ChoicesNumberArrayField(blank=True, choices=range(0, 24), default=list)),
                ('by_minute', my_django_app.fields.ChoicesNumberArrayField(blank=True, choices=range(0, 60), default=list)),
                ('by_second', my_django_app.fields.ChoicesNumberArrayField(blank=True, choices=range(0, 60), default=list)),
                ('by_set_position', my_django_app.fields.ChoicesNumberArrayField(blank=True, choices=range(-31, 32), default=list)),
                ('count', my_django_app.fields.OptionalLimitedDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', my_django_app.fields.DefaultTodayField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('end_date', my_django_app.fields.OptionalDateField(blank=True, null=True)),
                ('start_time', my_django_app.fields.OptionalLimitedTimeField(blank=True, null=True)),
                ('end_time', my_django_app.fields.OptionalLimitedTimeField(blank=True, null=True)),
                ('week_start', my_django_app.fields.ChoiceIntegerField([(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], 0)),
                ('title', my_django_app.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('is_archived', my_django_app.fields.DefaultBooleanField(False)),
                ('importance', my_django_app.fields.LimitedDecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
