# Generated by Django 5.2.4 on 2025-09-02 01:01

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_alter_task_importance_alter_task_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('task', my_django_app.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
