# Generated by Django 5.2.4 on 2025-09-02 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='freq',
            new_name='frequency',
        ),
    ]
