# Generated by Django 5.2.4 on 2025-08-07 14:35

import my_django_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('key', my_django_app.fields.ShortCharField(blank=True, default='', max_length=50, unique=True)),
                ('value', my_django_app.fields.LongCharField(blank=True, default='', max_length=1023)),
                ('description', my_django_app.fields.MediumCharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
