# Generated by Django 5.2.4 on 2025-08-05 12:59

import my_django_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('address', my_django_app.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('shelf', my_django_app.fields.ShortCharField(blank=True, default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
