# Generated by Django 5.2.4 on 2025-08-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_location_delete_warehouse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('address', 'shelf')},
        ),
    ]
