# Generated by Django 5.2.4 on 2025-08-08 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('product', '0003_alter_location_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Article',
        ),
    ]
