# Generated by Django 5.2.4 on 2025-08-09 05:31

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_product_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='purchase_price',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantity_per_unit',
            field=my_django_app.fields.LimitedIntegerField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='selling_price',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='categorycomponent',
            name='percent_cost',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='genericproduct',
            name='reorder_level',
            field=my_django_app.fields.LimitedIntegerField(),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='quantity',
            field=my_django_app.fields.LimitedIntegerField(),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='percent_cost',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, max_digits=10),
        ),
    ]
