# Generated by Django 5.2.4 on 2025-08-12 12:16

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_article_purchase_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('name', my_django_app.fields.MediumCharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=my_django_app.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.address'),
        ),
    ]
