# Generated by Django 5.2.4 on 2025-08-12 12:19

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_address_alter_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=my_django_app.fields.MediumCharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
