# Generated by Django 5.2.4 on 2025-08-14 06:07

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=my_django_app.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category'),
        ),
    ]
