# Generated by Django 5.2.4 on 2025-08-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_parent_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryComponent',
        ),
    ]
