# Generated by Django 5.2.4 on 2025-08-14 06:24

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_delete_categorycomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='parent_article',
            field=my_django_app.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.article'),
        ),
        migrations.DeleteModel(
            name='ProductComponent',
        ),
    ]
