# Generated by Django 5.2.4 on 2025-08-26 03:42

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_article_parent_article_delete_productcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericproduct',
            name='description',
            field=my_django_app.fields.MediumCharField(blank=True, default='', max_length=255),
        ),
    ]
