# Generated by Django 5.2.4 on 2025-08-27 10:21

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_genericproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='to_print_compatibility',
            field=my_django_app.fields.DefaultBooleanField(False),
        ),
        migrations.AddField(
            model_name='category',
            name='to_print_price',
            field=my_django_app.fields.DefaultBooleanField(False),
        ),
    ]
