# Generated by Django 5.2.4 on 2025-08-27 10:26

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category_to_print_compatibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='compatibility_image',
            field=my_django_app.fields.ImageField(blank=True, null=True, upload_to='compatibility'),
        ),
        migrations.AddField(
            model_name='category',
            name='pricelist_image',
            field=my_django_app.fields.ImageField(blank=True, null=True, upload_to='prices'),
        ),
    ]
