# Generated by Django 5.2.4 on 2025-08-28 04:03

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_category_compatibility_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='compatibility_file',
            field=my_django_app.fields.FileField(blank=True, null=True, upload_to='compatibility-csv'),
        ),
        migrations.AddField(
            model_name='category',
            name='pricelist_file',
            field=my_django_app.fields.FileField(blank=True, null=True, upload_to='prices-csv'),
        ),
    ]
