# Generated by Django 5.2.4 on 2025-08-29 00:52

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_category_compatibility_file_category_pricelist_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericproduct',
            name='is_generic',
            field=my_django_app.fields.DefaultBooleanField(False),
        ),
    ]
