# Generated by Django 5.2.4 on 2025-08-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_genericproduct_is_generic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericproduct',
            old_name='is_generic',
            new_name='is_article',
        ),
    ]
