# Generated by Django 5.2.4 on 2025-08-29 02:35

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_rename_is_generic_genericproduct_is_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='description',
            field=my_django_app.fields.LongCharField(blank=True, default='', max_length=1023),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='product',
            field=my_django_app.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.article'),
        ),
    ]
