# Generated by Django 5.2.4 on 2025-08-29 02:36

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_printjob_description_alter_printjob_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='font_sizes',
            field=my_django_app.fields.NumberArrayField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='printjob',
            name='purchase_code',
            field=my_django_app.fields.ShortCharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='printjob',
            name='selling_code',
            field=my_django_app.fields.ShortCharField(blank=True, default='', max_length=50),
        ),
    ]
