# Generated by Django 5.2.4 on 2025-08-29 03:59

import django.core.validators
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_printjob_font_sizes_printjob_purchase_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='height_mm',
            field=my_django_app.fields.LimitedIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(330)]),
        ),
        migrations.AddField(
            model_name='printjob',
            name='width_mm',
            field=my_django_app.fields.LimitedIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(216)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantity_per_unit',
            field=my_django_app.fields.LimitedIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='genericproduct',
            name='reorder_level',
            field=my_django_app.fields.LimitedIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='quantity',
            field=my_django_app.fields.LimitedIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
