# Generated by Django 5.2.4 on 2025-08-29 06:30

import django.core.validators
import django.db.models.deletion
import my_django_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_printjob_height_mm_printjob_width_mm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('width_mm', my_django_app.fields.LimitedIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(216)])),
                ('height_mm', my_django_app.fields.LimitedIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(330)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='height_mm',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='width_mm',
        ),
        migrations.AddField(
            model_name='printjob',
            name='dimension',
            field=my_django_app.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.printdimension'),
        ),
    ]
