# Generated by Django 5.2.4 on 2025-08-29 06:39

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_printdimension_remove_printjob_height_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printdimension',
            name='name',
            field=my_django_app.fields.ShortCharField(blank=True, default='', max_length=50),
        ),
    ]
