# Generated by Django 5.2.4 on 2025-08-29 09:28

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_printdimension_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='is_completed',
            field=my_django_app.fields.DefaultBooleanField(False),
        ),
    ]
