# Generated by Django 5.2.4 on 2025-08-29 12:35

import django.core.validators
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_printjob_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printdimension',
            name='width_mm',
            field=my_django_app.fields.LimitedIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(330)]),
        ),
    ]
