# Generated by Django 5.2.4 on 2025-09-02 00:50

import django.core.validators
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_printdimension_width_mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='purchase_price',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999.99)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='selling_price',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999.99)]),
        ),
    ]
