# Generated by Django 5.2.4 on 2025-09-23 01:06

import django.core.validators
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_article_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='piston_bore_00',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, default=40, max_digits=10, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='motor',
            name='piston_bore_100',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, default=40, max_digits=10, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='motor',
            name='piston_bore_150',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, default=40, max_digits=10, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='motor',
            name='piston_bore_200',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, default=40, max_digits=10, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='motor',
            name='piston_bore_25',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, default=40, max_digits=10, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='motor',
            name='piston_bore_50',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, default=40, max_digits=10, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='motor',
            name='piston_bore_75',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, default=40, max_digits=10, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='motor',
            name='piston_pin_size',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, default=10, max_digits=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
