# Generated by Django 5.2.4 on 2025-12-14 01:56

import django.core.validators
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_motor_piston_bore_00_motor_piston_bore_100_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='image',
            field=my_django_app.fields.ImageField(blank=True, null=True, upload_to='label_images/'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='img_height_mm',
            field=my_django_app.fields.LimitedIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='printjob',
            name='img_width_mm',
            field=my_django_app.fields.LimitedIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='printjob',
            name='is_q1_not_q3',
            field=my_django_app.fields.DefaultBooleanField(False),
        ),
    ]
