# Generated by Django 5.2.4 on 2025-12-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_printjob_image_printjob_img_height_mm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printjob',
            name='img_height_mm',
        ),
    ]
