# Generated by Django 5.2.4 on 2026-03-01 02:48

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_remove_printjob_img_height_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='is_repeated',
            field=my_django_app.fields.DefaultBooleanField(False),
        ),
    ]
