# Generated by Django 5.2.4 on 2025-08-05 13:19

import django.db.models.deletion
import my_django_app.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_payable_charge_receivable_charge'),
        ('people', '0001_initial'),
        ('product', '0003_alter_location_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('name', my_django_app.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('description', my_django_app.fields.MediumCharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('quantity', my_django_app.fields.LimitedIntegerField()),
                ('log_type', my_django_app.fields.ChoiceIntegerField([(0, 'Sale'), (1, 'Purchase'), (2, 'Return'), (3, 'Adjustment'), (4, 'Physical Count'), (5, 'Transfer')], 0)),
                ('product', my_django_app.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('receiver', my_django_app.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.location')),
                ('transmitter', my_django_app.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('status', my_django_app.fields.ChoiceIntegerField([(0, 'Draft'), (1, 'Pending Approval'), (2, 'Approved'), (3, 'Fulfilled'), (4, 'Cancelled')], 0)),
                ('inventory_logs', my_django_app.fields.OptionalManyToManyField(blank=True, to='commerce.inventorylog')),
                ('supplier', my_django_app.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.supplier')),
                ('transactions', my_django_app.fields.OptionalManyToManyField(blank=True, to='finance.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('status', my_django_app.fields.ChoiceIntegerField([(0, 'Draft'), (1, 'Pending Approval'), (2, 'Approved'), (3, 'Fulfilled'), (4, 'Cancelled')], 0)),
                ('customer', my_django_app.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.customer')),
                ('inventory_logs', my_django_app.fields.OptionalManyToManyField(blank=True, to='commerce.inventorylog')),
                ('transactions', my_django_app.fields.OptionalManyToManyField(blank=True, to='finance.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('purchase', my_django_app.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.purchase')),
                ('sale', my_django_app.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('description', my_django_app.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('cost', my_django_app.fields.AmountField(decimal_places=2, max_digits=10)),
                ('compensation_amount', my_django_app.fields.AmountField(decimal_places=2, max_digits=10)),
                ('is_paid', my_django_app.fields.DefaultBooleanField(False)),
                ('paid_at', my_django_app.fields.OptionalDateTimeField(blank=True, null=True)),
                ('employees', my_django_app.fields.OptionalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('labor_type', my_django_app.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.labortype')),
                ('sale', my_django_app.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
