# Generated by Django 5.2.4 on 2025-08-10 12:57

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('people', '0002_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='employees',
            field=my_django_app.fields.OptionalManyToManyField(blank=True, to='people.employee'),
        ),
    ]
