# Generated by Django 5.2.4 on 2025-08-11 03:04

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_labor_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=my_django_app.fields.ShortCharField(blank=True, default='', max_length=50),
        ),
    ]
