# Generated by Django 5.2.4 on 2025-08-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_sale_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='inventory_logs',
            new_name='sales_items',
        ),
    ]
