# Generated by Django 5.2.4 on 2025-08-11 09:00

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_rename_inventory_logs_sale_sales_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='inventory_logs',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sales_items',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='transactions',
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='purchase',
            field=my_django_app.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.purchase'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='sale',
            field=my_django_app.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.sale'),
        ),
    ]
