# Generated by Django 5.2.4 on 2025-08-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_remove_purchase_inventory_logs_and_more'),
        ('product', '0005_alter_article_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventorylog',
            constraint=models.UniqueConstraint(fields=('sale', 'product'), name='unique_sale_product'),
        ),
        migrations.AddConstraint(
            model_name='inventorylog',
            constraint=models.UniqueConstraint(fields=('purchase', 'product'), name='unique_purchase_product'),
        ),
    ]
