# Generated by Django 5.2.4 on 2025-08-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_inventorylog_unique_sale_product_and_more'),
        ('product', '0005_alter_article_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorylog',
            name='unique_sale_product',
        ),
        migrations.RemoveConstraint(
            model_name='inventorylog',
            name='unique_purchase_product',
        ),
        migrations.AddConstraint(
            model_name='inventorylog',
            constraint=models.UniqueConstraint(condition=models.Q(('sale__isnull', False)), fields=('sale', 'product'), name='unique_sale_product'),
        ),
        migrations.AddConstraint(
            model_name='inventorylog',
            constraint=models.UniqueConstraint(condition=models.Q(('purchase__isnull', False)), fields=('purchase', 'product'), name='unique_purchase_product'),
        ),
    ]
