# Generated by Django 5.2.4 on 2025-08-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_remove_inventorylog_unique_sale_product_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorylog',
            name='unique_sale_product',
        ),
        migrations.RemoveConstraint(
            model_name='inventorylog',
            name='unique_purchase_product',
        ),
    ]
