# Generated by Django 5.2.4 on 2025-08-12 13:14

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_remove_inventorylog_unique_sale_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=my_django_app.fields.ChoiceIntegerField([(0, 'Draft'), (1, 'Pending'), (2, 'Approved'), (3, 'Fulfilled'), (4, 'Cancelled')], 0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=my_django_app.fields.ChoiceIntegerField([(0, 'Draft'), (1, 'Pending'), (2, 'Approved'), (3, 'Fulfilled'), (4, 'Cancelled')], 0),
        ),
    ]
