# Generated by Django 5.2.4 on 2025-08-13 09:23

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_alter_purchase_status_alter_sale_status'),
        ('finance', '0007_transaction_purchase_transaction_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='collection',
            field=my_django_app.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transaction'),
        ),
    ]
