# Generated by Django 5.2.4 on 2025-08-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_labor_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labor',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='labor',
            name='paid_at',
        ),
    ]
