# Generated by Django 5.2.4 on 2025-08-13 11:22

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_remove_labor_is_paid_remove_labor_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='is_paid',
            field=my_django_app.fields.DefaultBooleanField(False),
        ),
    ]
