# Generated by Django 5.2.4 on 2025-08-14 01:45

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_rename_transmitter_inventorylog_coming_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='status',
            field=my_django_app.fields.ChoiceIntegerField([(1, 'Pending'), (2, 'Approved')], 0),
        ),
    ]
