# Generated by Django 5.2.4 on 2025-08-14 01:50

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_inventorylog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='status',
            field=my_django_app.fields.ChoiceIntegerField([(0, 'Pending'), (1, 'Approved')], 0),
        ),
    ]
