# Generated by Django 5.2.4 on 2025-08-14 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_alter_inventorylog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorylog',
            old_name='status',
            new_name='is_collected',
        ),
    ]
