# Generated by Django 5.2.4 on 2025-08-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_rename_status_inventorylog_is_collected'),
        ('product', '0010_article_parent_article_delete_productcomponent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventorylog',
            constraint=models.CheckConstraint(condition=models.Q(('coming_from', models.F('going_to')), _negated=True), name='inventorylog_cannot_equal_coming_from_going_to'),
        ),
    ]
