# Generated by Django 5.2.4 on 2025-08-15 00:24

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_inventorylog_inventorylog_cannot_equal_coming_from_going_to'),
        ('product', '0010_article_parent_article_delete_productcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('product', my_django_app.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('quantity', my_django_app.fields.AmountField(decimal_places=2, max_digits=10)),
                ('unit_amount', my_django_app.fields.AmountField(decimal_places=2, max_digits=10)),
                ('purchase', my_django_app.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.purchase')),
                ('unit', my_django_app.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemporarySaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('product', my_django_app.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('quantity', my_django_app.fields.AmountField(decimal_places=2, max_digits=10)),
                ('unit_amount', my_django_app.fields.AmountField(decimal_places=2, max_digits=10)),
                ('sale', my_django_app.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.sale')),
                ('unit', my_django_app.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
