# Generated by Django 5.2.4 on 2025-08-15 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_temporarypurchaseitem_temporarysaleitem'),
        ('product', '0010_article_parent_article_delete_productcomponent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemporaryPurchaseItem',
            new_name='TemporaryPurchase',
        ),
        migrations.RenameModel(
            old_name='TemporarySaleItem',
            new_name='TemporarySale',
        ),
    ]
