# Generated by Django 5.2.4 on 2025-08-15 01:03

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0020_rename_temporarypurchaseitem_temporarypurchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarysale',
            name='quantity',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, max_digits=10),
        ),
    ]
