# Generated by Django 5.2.4 on 2025-08-15 11:51

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_alter_temporarysale_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarypurchase',
            name='quantity',
            field=my_django_app.fields.LimitedDecimalField(decimal_places=2, max_digits=10),
        ),
    ]
