# Generated by Django 5.2.4 on 2025-08-20 06:52

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_alter_temporarypurchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='image',
            field=my_django_app.fields.ImageField(null=True, upload_to='prints'),
        ),
    ]
