# Generated by Django 5.2.4 on 2025-08-20 07:08

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0023_printjob_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='purchase',
            field=my_django_app.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.purchase', unique=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='sale',
            field=my_django_app.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.sale', unique=True),
        ),
    ]
