# Generated by Django 5.2.4 on 2025-09-01 07:44

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0027_alter_printjob_purchase_alter_printjob_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='receipt',
            field=my_django_app.fields.ImageField(blank=True, null=True, upload_to='purchases-receipts'),
        ),
    ]
