# Generated by Django 5.2.4 on 2025-09-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0028_purchase_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='receipt',
            new_name='receipt_image',
        ),
    ]
