# Generated by Django 5.2.4 on 2025-09-01 07:52

import my_django_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0029_rename_receipt_purchase_receipt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('image', my_django_app.fields.ImageField(blank=True, null=True, upload_to='receipts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='receipt_image',
        ),
        migrations.AddField(
            model_name='purchase',
            name='receipt_images',
            field=my_django_app.fields.OptionalManyToManyField(blank=True, to='commerce.receiptimage'),
        ),
    ]
