# Generated by Django 5.2.4 on 2025-09-01 07:59

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0030_receiptimage_remove_purchase_receipt_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptimage',
            name='date',
            field=my_django_app.fields.OptionalDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptimage',
            name='issuer',
            field=my_django_app.fields.ShortCharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='receiptimage',
            name='receipt_no',
            field=my_django_app.fields.ShortCharField(blank=True, default='', max_length=50),
        ),
    ]
