# Generated by Django 5.2.4 on 2025-09-04 03:19

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0031_receiptimage_date_receiptimage_issuer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='to_print',
            field=my_django_app.fields.DefaultBooleanField(False),
        ),
    ]
