# Generated by Django 5.2.4 on 2025-09-05 00:39

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0032_printjob_to_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='to_print',
            field=my_django_app.fields.DefaultBooleanField(False),
        ),
    ]
