# Generated by Django 5.2.4 on 2025-09-05 00:41

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0033_sale_to_print'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('image', my_django_app.fields.ImageField(blank=True, null=True, upload_to='sale-receipts')),
                ('sale', my_django_app.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
