# Generated by Django 5.2.4 on 2025-09-05 01:17

import django.core.validators
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0034_salereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereceipt',
            name='page_number',
            field=my_django_app.fields.LimitedIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='salereceipt',
            name='total_pages',
            field=my_django_app.fields.LimitedIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
