# Generated by Django 5.2.4 on 2025-09-05 01:21

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0035_salereceipt_page_number_salereceipt_total_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereceipt',
            name='to_print',
            field=my_django_app.fields.DefaultBooleanField(False),
        ),
    ]
