# Generated by Django 5.2.4 on 2025-08-05 11:02

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('name', my_django_app.fields.ShortCharField(blank=True, default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('title', my_django_app.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('nature', my_django_app.fields.ChoiceIntegerField([(0, 'Outgoing'), (1, 'Incoming'), (2, 'Transfer'), (3, 'Receivable'), (4, 'Payable')], 0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('description', my_django_app.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('amount', my_django_app.fields.AmountField(decimal_places=2, max_digits=10)),
                ('category', my_django_app.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('receiver', my_django_app.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account')),
                ('transmitter', my_django_app.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('name', my_django_app.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('amount', my_django_app.fields.AmountField(decimal_places=2, max_digits=10)),
                ('description', my_django_app.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('date_due', my_django_app.fields.OptionalDateField(blank=True, null=True)),
                ('date_completed', my_django_app.fields.OptionalDateField(blank=True, null=True)),
                ('payments', my_django_app.fields.OptionalManyToManyField(blank=True, to='finance.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('name', my_django_app.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('amount', my_django_app.fields.AmountField(decimal_places=2, max_digits=10)),
                ('description', my_django_app.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('date_due', my_django_app.fields.OptionalDateField(blank=True, null=True)),
                ('date_completed', my_django_app.fields.OptionalDateField(blank=True, null=True)),
                ('payments', my_django_app.fields.OptionalManyToManyField(blank=True, to='finance.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
