# Generated by Django 5.2.4 on 2025-08-05 12:36

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='charge',
            field=my_django_app.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='charge',
            field=my_django_app.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.transaction'),
        ),
    ]
