# Generated by Django 5.2.4 on 2025-08-10 23:52

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payable_charge_receivable_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=my_django_app.fields.ChoiceIntegerField([(0, 'Cash'), (1, 'Coins'), (2, 'Debit'), (3, 'Credit'), (4, 'Untracked')], 0),
        ),
    ]
