# Generated by Django 5.2.4 on 2025-08-10 23:55

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=my_django_app.fields.ChoiceIntegerField([(0, 'Cash'), (1, 'Coins'), (3, 'Mixed'), (4, 'Debit'), (5, 'Credit'), (6, 'Untracked')], 0),
        ),
    ]
