# Generated by Django 5.2.4 on 2025-08-11 01:07

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=my_django_app.fields.ChoiceIntegerField([(0, 'Cash'), (1, 'Coins'), (3, 'Cash + Coins'), (4, 'Savings'), (5, 'Credit'), (6, 'Loan'), (7, 'Mortgage'), (8, 'Stocks'), (9, 'Assets'), (10, 'Liabilities'), (11, 'Untracked')], 0),
        ),
    ]
