# Generated by Django 5.2.4 on 2025-08-11 09:00

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_remove_purchase_inventory_logs_and_more'),
        ('finance', '0006_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='purchase',
            field=my_django_app.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.purchase'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sale',
            field=my_django_app.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.sale'),
        ),
    ]
