# Generated by Django 5.2.4 on 2025-08-14 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_transaction_purchase_transaction_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transmitter',
            new_name='coming_from',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver',
            new_name='going_to',
        ),
    ]
