# Generated by Django 5.2.4 on 2025-08-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_rename_status_inventorylog_is_collected'),
        ('finance', '0008_rename_transmitter_transaction_coming_from_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('coming_from', models.F('going_to')), _negated=True), name='transaction_not_self_transfer'),
        ),
    ]
