# Generated by Django 5.2.4 on 2025-08-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_rename_status_inventorylog_is_collected'),
        ('finance', '0009_transaction_transaction_not_self_transfer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_not_self_transfer',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('coming_from', models.F('going_to')), _negated=True), name='cannot_equal_coming_from_going_to'),
        ),
    ]
