# Generated by Django 5.2.4 on 2025-08-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_inventorylog_inventorylog_cannot_equal_coming_from_going_to'),
        ('finance', '0010_remove_transaction_transaction_not_self_transfer_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='cannot_equal_coming_from_going_to',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('coming_from', models.F('going_to')), _negated=True), name='transaction_cannot_equal_coming_from_going_to'),
        ),
    ]
