# Generated by Django 5.2.4 on 2025-08-15 06:32

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_alter_temporarysale_quantity'),
        ('finance', '0011_remove_transaction_cannot_equal_coming_from_going_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='labor',
            field=my_django_app.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.labor'),
        ),
    ]
