# Generated by Django 5.2.4 on 2025-08-15 13:22

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_transaction_labor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=my_django_app.fields.ChoiceIntegerField([(0, 'Cash'), (1, 'Coins'), (2, 'Cash + Coins'), (3, 'Savings'), (4, 'Credit'), (5, 'Loan'), (6, 'Mortgage'), (7, 'Stocks'), (8, 'Assets'), (9, 'Liabilities'), (10, 'Untracked')], 0),
        ),
    ]
