# Generated by Django 5.2.4 on 2025-08-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payable',
            name='date_completed',
        ),
    ]
