# Generated by Django 5.2.4 on 2025-08-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_remove_payable_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivable',
            name='date_completed',
        ),
    ]
