# Generated by Django 5.2.4 on 2025-09-03 06:03

import django.db.models.deletion
import my_django_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_remove_receivable_date_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', my_django_app.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', my_django_app.fields.AutoUpdatedAtField(auto_now=True)),
                ('image', my_django_app.fields.ImageField(blank=True, null=True, upload_to='transactions')),
                ('name', my_django_app.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('date', my_django_app.fields.OptionalDateField(blank=True, null=True)),
                ('transaction', my_django_app.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
