# Generated by Django 5.2.4 on 2025-09-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_transactionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionimage',
            name='name',
        ),
    ]
