# Generated by Django 5.2.4 on 2025-09-03 06:16

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_remove_transactionimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_print',
            field=my_django_app.fields.DefaultBooleanField(False),
        ),
    ]
