# Generated by Django 5.2.4 on 2025-09-03 06:34

import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_transaction_to_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image',
            field=my_django_app.fields.ImageField(blank=True, null=True, upload_to='transactions'),
        ),
        migrations.DeleteModel(
            name='TransactionImage',
        ),
    ]
