# Generated by Django 5.2.4 on 2025-11-22 01:58

import django.utils.timezone
import my_django_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_transaction_image_delete_transactionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='datetime_transacted',
            field=my_django_app.fields.DefaultNowField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
